### PR TITLE
ruplacer 0.6.4

### PR DESCRIPTION
**Pull request by maximerety**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by Masynchin** [comment]
It will need to update `ruplacer` repo README with new brew link?

**Comment by maximerety** [comment]
> It will need to update `ruplacer` repo README with new brew link?

The old link should continue to work as there is a redirection from `TankerHQ` to `dmerejkowsky`, but sure it will be cleaner to update the README in the `ruplacer` repo.

I'll get to it as soon as @dmerejkowsky reviews this MR 😉

**Comment by Masynchin** [comment]
Now it installing last version with `brew install dmerejkowsky/homebrew-repo/ruplacer`. One little problem now is that `brew info ruplacer` results with error because of:
```
Formulae found in multiple taps:
* tankerhq/repo/ruplacer
* dmerejkowsky/repo/ruplacer
```

**Comment by dmerejkowsky** [comment]
Not sure this can be fixed :(

**Comment by Masynchin** [comment]
> Not sure this can be fixed :(

It not such a problem, I just wanted to check installed version. It works correctly with full formulae

**Comment by maximerety** [comment]
@Masynchin I think you can fix this by "forgetting" about the old tap, e.g.

```bash
brew untap -f tankerhq/repo/ruplacer
```

Would you be able to give it a try and confirm this fixes the problem?

**Edit**: added the `-f` flag as `brew` may complain about the tap still containing the ruplacer formula 😉

**Comment by Masynchin** [comment]
> Would you be able to give it a try and confirm this fixes the problem?

Both (original and edited) exact commands results error `Error: Invalid tap name 'tankerhq/repo/ruplacer'`, but `brew untap tankerhq/repo` successfully untaps repo.

**Comment by maximerety** [comment]
My mistake. Thanks for the confirmation though!

**Pull request merged**
